### PR TITLE
Make ListBlocks() compatible with BlockAffinityKey

### PR DESCRIPTION
**Pull request by jasonjoo2010**
att

### CODE REVIEW

**Comment by jasonjoo2010** [comment]
@nyanpassu

**Comment by jasonjoo2010** [comment]
pls look look

**Comment by CMGS** [comment]
codacy static show warning

**Comment by jasonjoo2010** [comment]
CI was fucked? @CMGS

**Comment by CMGS** [comment]
lint and codacy fucked, add notes before the public func

**Comment by jasonjoo2010** [comment]
How?

**Pull request merged**
